language: go
go:
- '1.15'
env:
  global:
    secure: P3rZKSrfPKKk7BRgoWms/6S8VAiX75CtVGqo7gn3gBIkBbJG9iPlTHtjIwMkRKF3wN1TYCefXFsx0hgN9RgjFWe2/0OOJf2xI2sxtmxW0JhgWeIQUSz0suFvWKCu9ooxLd//DqtxsVH4YiyxVVd3Uc/ALtyUtG/6V5WVdXnla9MscFRVncHiUKyTzWwwyJSkhNZ8uhpw32He0ko4w5ksZ3JV+FOmb6xKahCpZaZSnhVvErH1SgrtL1T491jg6MGp1EcpeiMsDnsvProWf+bTra/9nOelGQfEuwtVSr0QyF4vRHe/Q+a7z9pjqZ526VU9tN5JvSkV71sL0h+Kr4OCJNT7LphN4O6ShlbTBIN2HJ0wC0N1D9ygg1Lzb2hcDJv9x4Bhn1x8HuhK74f7dQ/oJTlBStKMVs0MqNQE9O9Ur0YtqyTi8xNIe0WdGCuCDvO2JxqVtX9F/VaDc81mAbfsruiPwQhYF9xGesMrpCa8w/kBrAMH/mzwxHpEqO37Y2JCK3VOHi9lUcEgcNjGXRlY1i0NgcqY/UeyO9MtAz/54XLrNK3ShbIYhii+8kC/G1pvZSPVdWUGO+Nk2/XxluJl5rT4YTD5hWqyqYnlGgQIcJxWQxTdqhaphQyz2qdv1TVWSSR9KGtknUGGjbteeyx//A7AWO0KEx6B80ttR+Oi1NU=
